apiVersion: v1
kind: Secret
metadata:
  name: account-secret
type: Opaque
data:
  PaymentSettings__AccessKey: VnVvbmdOdlJlYWN0
  PaymentSettings__SecretKey: SUdLYzN2ZGZXZ2ZXQll3aENmZkF2ZHVjcE9OeHRjaUlndw==