apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
data:
    ConnectionStrings__Default: U2VydmVyPTY4LjE4My4yMzUuMTk1O1BvcnQ9NTQzMjtEYXRhYmFzZT1jYXRhbG9nO1VzZXIgSWQ9cG9zdGdyZXM7UGFzc3dvcmQ9cmVhY3Rqcw==
    KeycloakSetting__Url: aHR0cDovL2F1dGgub210ZXN0Lm9ubGluZQ==
    KeycloakSetting__ClientSecret: NGUzNDU0YWMtYTVjYi00YmRlLWIzNDYtMWU3N2Y3ODAzNzA0
    KeycloakSetting__ClientId: cmVhdGpzLWFwcA==
    KeycloakSetting__Username: dnVvbmdudg==
    KeycloakSetting__Password: VkBuRmRrMTJjIQ==
    KafkaSettings__BootstrapServers: bG9jYWxob3N0OjkwOTM=
    ServiceConfig__serviceDiscoveryAddress: aHR0cDovLzY4LjE4My4yMzUuMTk1Ojg1MDA=
    ServiceConfig__serviceAddress: aHR0cDovL2xvY2FsaG9zdDo0NDM4NQ==