import {
  ACCOUNT_SERVICE_URL,
  AUTHENTICATE_URL,
  CATALOG_SERVICE_URL,
  EXAMINATION_URL,
  ORIGIN_URL,
} from 'constants/urlApi';

export const API_URL = ORIGIN_URL + CATALOG_SERVICE_URL;
export const BASE_URL = ORIGIN_URL;
export const AUTH_URL = AUTHENTICATE_URL + ACCOUNT_SERVICE_URL;
export const EXAM_URL = EXAMINATION_URL;